name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new version to set"
        required: true
      following_version:
        description: "The post (dev) version to set"
        required: false
      dry_run:
        description: "Dry Run?"
        default: false
        type: boolean
  schedule:
    - cron:  '30 5 * * *'

env:
  # Changes per repo
  PRODUCT_NAME: Motor
  # Changes per branch
  SILK_ASSET_GROUP: motor
  EVERGREEN_PROJECT: motor
  # Constant
  DRY_RUN: ${{ inputs.dry_run || 'true' }}
  FOLLOWING_VERSION: ${{ inputs.following_version || '' }}
  VERSION: ${{ inputs.version || '10.10.10.10' }}

defaults:
  run:
    shell: bash -eux {0}

jobs:
  pre-publish:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "DRY RUN: ${DRY_RUN}"
          echo "VERSION: ${VERSION}"
          echo "FOLLOWING_VERSION: ${FOLLOWING_VERSION}"
